### ISSUE TITLE
Escript Troubles

### ISSUE THREAD

**Issue by andyl** [fhunleth/muontrap#35] opened 2022-01-14 01:12 UTC
Using Muontrap in :dev and :test - all good.

When running in an Escript, I get an error `ArgumentError unknown application :muontrap`.

This comes from `MuonTrap.Port#muontrap_path/0`:  `Application.app_dir(:muontrap, ["priv", "muontrap"])`

When I look in the `_build` directory I can see the `/priv/muontop` executable...

Does anyone have an idea of why this is failing in an Escript?

**Comment by andyl** [comment] 2022-01-14 03:23
FYI I posted a simple Elixir repo which recreates the issue.  See https://github.com/andyl/zing

**Comment by fhunleth** [comment] 2022-01-14 05:02
Just a thought, but does `Application.app_dir/2` work for other libraries with Escripts? I'm not sure what `muontrap` would have done to break this that would be unique to it.

**Comment by axelson** [comment] 2022-01-14 09:10
Yeah I think the issue is that `Application.app_dir/2` doesn't work with escripts because there is no app directory for dependencies of an escript (although that may not be the 100% correct way of writing that). @andyl if it works for you maybe you could try using https://github.com/burrito-elixir/burrito instead of an script since I _think_ deps will have an application directory then.

Although another alternative is to modify muontrap so it doesn't depend on `Application.app_dir/2` and copy the binary manually and pass the path to the binary to muontrap. But that's rather invasive.

But for a partial example of what the calling code for that would look like you can take a look at how I handled it for erlexec:
https://github.com/axelson/ls_proxy/blob/6ae090620f4c1e9c95c403515cda3719f89862b2/ls_proxy/lib/erlexec_init.ex

A third alternative would be use erlexec (or its [exexec](https://hex.pm/packages/exexec) wrapper) directly since it fulfills a similar goal to muontrap, unless what you needed was the cgroup support.

**Comment by fhunleth** [comment] 2022-01-14 13:58
+1 to use Burrito instead of Escripts. That will work since you'll be making and running an OTP release.

That's an interesting workaround to Escripts for erlexec. If the only change to `muontrap` is to add an option supplying a port binary path and using it in preference to calling `Application.app_dir/2` in `muontrap`, then that doesn't sound like a big change. (Given that `erlexec` works already, though, that does sound like possibly the easiest change.)

**Comment by andyl** [comment] 2022-01-14 15:33
@axelson and @fhunleth - thanks for the guidance.  I'll give it a try with Burrito and post here when I have some results.

**Comment by andyl** [comment] 2022-01-14 17:37
From my Linux dev box I couldn't get Burrito to cross compile.  I expect because Burrito is new and not yet fully tested.  

Other than that Burrito runs MuonTrap as expected & looks like a good workaround!

The MuonTrap / Burrito demo is at https://github.com/andyl/mt_demo 

MuonTrap is super nice!  Thanks again for the tips.

**Comment by fhunleth** [comment] 2022-01-15 15:55
Thanks for the update! Burrito is actively being worked on so, I expect it to get better. I really like the Burrito approach for this so I'm going to close this. Let me know if you have any other issues.

**Closed by fhunleth** 2022-01-15 15:55 UTC
